apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.host }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Release.Name }}.{{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-app
          servicePort: 80
