version: "3.3"
services:
  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=a010o8h84pk67510o8h   
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6572:6379
  server:
    image: sris-dev:latest
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3503:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: a010o8h84pk67510o8h
      DB_USER_NAME: admin
      DB_SYNC: "true"
      DB_LOG: "false"
      PORT: 3000
      PROD: "true"
      HOST: https://dev.sris.biip.lt
      SAVIVALDYBES_GEOSERVER: http://geo.biip.lt
      E_VARTAI_HOST: https://vartai.biip.lt
      WP_URL: https://biip.w8.lt
      UETK_PROXY: http://195.182.74.140
      MINIO_ENDPOINT: s3.gamta.online
      MINIO_PORT: 80
      QGIS: http://gis.biip.lt
      MINIO_USESSL: "false"
      MINIO_ACCESSKEY: "dwqasdasdwqeeq51421513"
      MINIO_SECRETKEY: "adsqwweqasdt15363161dasca2"
      MONGO_LOG: mongodb://admin:a010o8h84pk67510o8h@mongodb:27017
      POSTMARK_KEY: "e8df00fb-708f-4413-9c3b-1eac636d3432"
      MAIL_FROM: "noreply@biip.lt"
  db:
    image: postgres:latest
    restart: always
    expose:
      - 6513
    ports:
      - 6513:5432
    environment:
      POSTGRES_PASSWORD: "a010o8h84pk67510o8h"
      POSTGRES_USER: "admin"
